name: Run tests on a pr

on: push
env:
  # global env to all steps
  TOX_WORKERS: -n2

permissions:
  contents: read

jobs:
  run-test-amd64:
    name: test-amd64-${{ matrix.python-version }}-${{ matrix.build-type }}-${{ matrix.architecture
      }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # run this job using this matrix, excluding some combinations below.
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.11'
        build-type:
        - cext
        - nocext
        architecture:
        - x64
      # abort all jobs as soon as one fails
      fail-fast: false

    # steps to run in each job. Some are github actions, others run shell commands
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade tox setuptools
        pip list

    - name: Run tests
      run: tox -e github-${{ matrix.build-type }} -- -q --nomemory --notimingintensive
        ${{ matrix.pytest-args }}
